# Branch Protection Rules for main branch
# This file documents the recommended branch protection settings

# Required Status Checks:
# - test (from .github/workflows/ci.yml)
# - build (from .github/workflows/ci.yml)

# Branch Protection Rules to enable in GitHub:
# 1. Require a pull request before merging
# 2. Require status checks to pass before merging
# 3. Require branches to be up to date before merging
# 4. Require conversation resolution before merging
# 5. Restrict pushes that create files that are larger than 100 MB

# Status Checks Required:
# - test: Run Tests
# - build: Build project

# Additional Settings:
# - Dismiss stale PR approvals when new commits are pushed
# - Require review from code owners
# - Restrict deletions
